version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "//"
  schedule:
    interval: weekly
    day: saturday
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "///"
  schedule:
    interval: weekly
    day: sunday
    time: "07:00"
  open-pull-requests-limit: 10
