name: Automerge and Update Plots

# Controls when the action will run. 
on:
  pull_request_target:
  # Allows you to run this workflow manually from the Actions tab, only use for testing
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  create-plots:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .
      - name: Update plots
        run: |
          echo "Updating plots on ${GITHUB_HEAD_REF#refs/heads/}"
          python .github/update_plots.py
      - name: Setup git
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions
          git add .github/*.png
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Upload files
        if: steps.changes.outputs.changed == 1
        run: |
          python .github/update_date.py
          git add .github/date_last_updated.yml
          git commit --message 'Update plots'
          git remote remove origin
          git remote add origin https://${{ secrets.PA_TOKEN }}@github.com/slwatkins/covid.git
          echo "Pushing to ${GITHUB_HEAD_REF#refs/heads/}"
          git push --quiet origin HEAD:"${GITHUB_HEAD_REF#refs/heads/}" > /dev/null 2>&1
  dependabot-merge:
    name: Merge dependabot updates
    needs: [create-plots]
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge Dependabot PR
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 10
          retry_on: error
          command: gh pr merge --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
