name: Auto-Merge Pull Requests

# Controls when the action will run. 
on:
  pull_request_target:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          github-token: ${{ secrets.PA_TOKEN }}
