name: Auto-Merge Pull Requests

# Controls when the action will run. 
on:
  pull_request_target:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    name: Auto merge dependabot PR
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Auto merge dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2.3
        with:
          target: minor
          github-token: ${{ secrets.PA_TOKEN }}
